### ISSUE TITLE
The configuration tree has no root node

### ISSUE THREAD

**Issue by markitosgv** [wobblecode/WobbleCodeRestBundle#17]
When installing this bundle on Symfony 4 it throws this error 'The configuration tree has no root node'.
This bundle not need configuration file, then it can be deleted and it works ok.

**Comment by luishdez** [comment]
Can you elaborate this ? I'm using it with sf4 and I haven't seen that error. 

What do you meen when "it can be deleted" the configuration file ? Is this file part of this bundle or some file generated by Symfony Flex?

**Comment by markitosgv** [comment]
Hi Luis,

It's in Symfony 4.1. Look at this: https://github.com/symfony/symfony/issues/27450

The solution is to fix DependencyInjection/Configuration.php, or delete it beacuse in this bundle configuration is not needed.

**Comment by markitosgv** [comment]
Solved in #19

**Comment by luishdez** [comment]
I see, thanks for the PR
